version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1-browsers
    steps:
      - run:
          name: Download Apple Auth Example
          command: |
            git clone https://github.com/ananay/apple-auth-example.git
            cd apple-auth-example
      - run:
          name: Download Apple Auth
          command: |
            cd /home/circleci/project/apple-auth-example
            npm install git+https://github.com/ananay/apple-auth
      - run:
          name: Run node app
          command: |
            cd /home/circleci/project/apple-auth-example
            node src/app.js 

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only: master
          pull_requests:
            only: /^feature\//
