version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Add pull request as dependency
          command: |
            git clone https://github.com/ananay/apple-auth-example.git
            cd apple-auth-example
            npm install git+https://github.com/ananay/apple-auth

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only: master
          pull_requests:
            only: /^feature\//
